# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Create app directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends git gh \
    && rm -rf /var/lib/apt/lists/*

# Copy Python project
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir .

# Default command
CMD ["yellhorn-mcp"]
